### ISSUE TITLE
Question about parameter in README

### ISSUE THREAD

**Issue by sameerd** [RomeroLab/pudms#1]
I get this error when trying to follow the README. 

```
Error in pudms(protein_dat = smpl_dat, py1 = protein_py1, order = 1, aggregate = T,  : 
  unused argument (aggregate = T)
```

https://github.com/RomeroLab/pu-learning/blob/7c837e3f421bd25f145ed009d7ea0ce1d7c1c421/README.Rmd#L78-L83

@hsong1  Should I remove the line `aggregate=T`?

**Comment by hsong1** [comment]
README file has been updated!

**Comment by philromero** [comment]
The same fixed basestate for all positions? This function is already internally implemented; so I can make the option available in pudms function if desired.


On Mar 26, 2020, at 12:09 PM, Philip Romero <promero2@wisc.edu<mailto:promero2@wisc.edu>> wrote:

One thing I remember I wanted being fixed was to include a fixed basestate in create_model_frame.  This is important for chimeras.  I remember I had to modify something in the pudms code to include:

Xprotein = create_model_frame(grouped_dat = pu_data,order = model_order, basestate = 'A')

Maybe we could have an option "mostcommon" or "fixed"?  Not quite sure of the simplest implementation.

On Thu, Mar 26, 2020 at 10:55 AM hsong1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1<https://github.com/RomeroLab/pu-learning/issues/1>.

**Comment by philromero** [comment]
One thing I remember I wanted being fixed was to include a fixed basestate
in create_model_frame.  This is important for chimeras.  I remember I had
to modify something in the pudms code to include:

Xprotein = create_model_frame(grouped_dat = pu_data,order = model_order,
basestate = 'A')


Maybe we could have an option "mostcommon" or "fixed"?  Not quite sure of
the simplest implementation.

**Comment by hsong1** [comment]
Yes, just to make sure, the same base state for every position? I can make a change in pudms function to include the option.

**Comment by philromero** [comment]
I think same base for every position.  There are two main use cases:
1. DMS where the base sequence should be the most frequent
2. Chimeras where the base sequence should be the same over all positions
